name: Artemis
version: '0.0.0'
main: fr.oxozot.artemis.Artemis
api-version: '1.21'
authors: [ Oxozot, Kayrouge ]
commands:
  test:
    permission: artemis.testcmd
    description: ceci est une commande de test
    usage: /test
  switchMode:
    description: Permet au joueur de changer sa pioche de mode (necessite une pioche de diamant ou plus)
    usage: /switchMode
